spring.application.name=eureka-server
server.port=8761

# Standalone mode: Eureka server does not register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

