spring.application.name=usermanagement
server.port=8081


# PostgreSQL DataSource (required by DataSourceConfig)
spring.cloud.gcp.sql.instance-connection-name=ovacp-db:europe-west3:ovacp
spring.cloud.gcp.sql.database-name=ovacp-database
spring.datasource.username=postgres
spring.datasource.password=post123.PWD
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Die IP-Adresse statt Hostname nutzen (stabiler in Testumgebungen)
eureka.instance.prefer-ip-address=true

# Verzögert die Registrierung, damit der Context Zeit zum Atmen hat
eureka.client.enabled=true
# Wichtig: Wir zwingen die App, den DNS-Lookup/Initialisierung zu puffern
eureka.client.should-enforce-registration-at-init=true
spring.cloud.service-registry.auto-registration.enabled=false